version: 2
defaults: &defaults
    docker:
      - image: docker:17.11.0-ce-git        
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            apk add --no-cache bash
            apk add --no-cache jq py-pip sudo
            sudo pip install awscli --upgrade 
restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-lsp-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-lsp-{{ checksum "package-lock.json" }}
  paths:
    - node_modules           

jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - restore_cache: *restore_cache_settings_for_build
      - run: ./build.sh DEV
      - save_cache: *save_cache_settings          
      - deploy:
          name: Running Masterscript.
          command: |
            git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deply_v4.2.sh .
            ./master_deply_v4.2.sh -d ECS -e DEV -t $CIRCLE_SHA1 -s member-group-processor
  # Build & Deploy against production backend
  "build-prod":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - restore_cache: *restore_cache_settings_for_build
      - restore_cache: *restore_cache_settings_for_build
      - run: ./build.sh PROD
      - save_cache: *save_cache_settings          
      - deploy:
          name: Running Masterscript.
          command: |
            git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deply_v4.2.sh .
            ./master_deply_v4.2.sh -d ECS -e PROD -t $CIRCLE_SHA1 -s member-group-processor
            
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          filters:
            branches:
              only:
                - dev-circleci2
                - develop

      # Production builds are exectuted only on tagged commits to the
      # master branch.
      - "build-prod":
          filters:
            branches:
              only: master
