version: '3'
services:
  member-group-processor:
    image: member-group-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
